name: CI-CD

on:
  push:
    branches: [main]

jobs:
  gcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v2'

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCLOUD_DEPLOY }}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'somerandom'
        runtime: 'python38'
